### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by rdeusser** [mirweb/taskboard-docker#1]
After running:

```
docker pull mirweb/taskboard
docker run -d -p 80:80 mirweb/taskboard
```

I am unable to login with username: admin and password: admin. There are no errors. The page just reloads. Just in case, I made sure the api/ folder was writable. Any ideas?

**Comment by mirweb** [comment]
Sorry, at the moment my project is not ready. I suggest build an image from the original dockerfile from the [TaksBorad](https://github.com/kiswa/TaskBoard) Github-Project. It is located under build-Folder.

**Comment by mirweb** [comment]
New version is uploaded, with fixed apache-conf
